name: Generate New Keystore
on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v -keystore new-beerdex.keystore -alias beerdex-key -keyalg RSA -keysize 2048 -validity 10000 -storepass beerdex-secret -keypass beerdex-secret -dname "CN=Beerdex, OU=Dev, O=Beerdex, L=Brussels, C=BE"
          keytool -export -rfc -keystore new-beerdex.keystore -alias beerdex-key -file upload_certificate.pem -storepass beerdex-secret
          
      - name: Get Base64
        run: |
          base64 new-beerdex.keystore | tr -d '\n' > keystore_base64.txt
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: new-keystore-files
          path: |
            new-beerdex.keystore
            upload_certificate.pem
            keystore_base64.txt
